services:
  app:
    build:
      context: .
    container_name: dev-app # Bu satır eklendi!
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web # Statik ve medya dosyaları için
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost
      - WATERMARK_ENABLED=False
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: dev-db # Bu satır eklendi!
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432" # DBeaver gibi harici araçlarla bağlanmak için
    volumes:
      - dev_db_data:/var/lib/postgresql/data

# Volume tanımı
volumes:
  dev_db_data: