"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG', 0)))

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(
    filter(
        None,
        os.environ.get('ALLOWED_HOSTS', '').split(','),
    )
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local Apps
    'users.apps.UsersConfig',
    'core.apps.CoreConfig',

    # Third Party Apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'imagekit',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'app.urls'
AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.environ.get('DB_HOST'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# Bu URL, web tarayıcısının statik dosyalara erişmek için kullanacağı önektir.
# Genellikle '/static/' olarak ayarlanır. Nginx de bu URL'i dinler.
STATIC_URL = '/static/'

# Medya dosyaları (kullanıcı tarafından yüklenen resimler, videolar vb.)
# Bu URL, web tarayıcısının medya dosyalarına erişmek için kullanacağı önektir.
# Genellikle '/media/' olarak ayarlanır. Nginx de bu URL'i dinler.
MEDIA_URL = '/media/'

# 'python manage.py collectstatic' komutunun statik dosyaları toplayacağı dizin.
# Bu dizin, Docker volume'ü aracılığıyla hem uygulama hem de Nginx konteynerleri tarafından paylaşılacaktır.
MEDIA_ROOT = '/vol/web/media'

# Kullanıcı tarafından yüklenen medya dosyalarının saklanacağı dizin.
# Bu dizin de Docker volume'ü aracılığıyla paylaşılacaktır.
STATIC_ROOT = '/vol/web/static'

# Geliştirme sırasında Django'nun statik dosyaları arayacağı ek dizinler.
# 'BASE_DIR / "static"' genellikle Django uygulamanızın kendi statik dosyalarını içerir.
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

IMAGEKIT_SPEC_CACHEFILE_NAMING_SCHEME = 'source_path_as_hash' # veya 'spec_slug'
IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = 'imagekit.cachefiles.strategies.JustInTime' # Varsayılan bu olmalı
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TinyMCE Ayarları
TINYMCE_JS_URL = STATIC_URL + "tinymce/tinymce.min.js"
TINYMCE_COMPRESSOR = False # Geliştirme ortamında False olması iyi
TINYMCE_SPELLCHECKER = False # İsteğe bağlı
TINYMCE_TOOLBAR = "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor backcolor | formatselect fontsizeselect" # Temel toolbar düğmeleri
TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'menubar': 'file edit view insert format tools table help',
    'plugins': 'advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount autoresize',
    'toolbar': TINYMCE_TOOLBAR,
    'custom_undo_redo_levels': 10,
    'paste_data_images': True, # Resimleri doğrudan yapıştırma (isteğe bağlı)
    'relative_urls': False, # Göreli URL'leri kapatır
    'remove_script_host': True,
    'convert_urls': False,
    'image_title': True,
    'automatic_uploads': True,
    'file_picker_types': 'image',
    'file_picker_callback': 'tinymce_file_picker', # Resim yükleyici için özel fonksiyon
    'images_upload_url': '/tinymce/upload/', # TinyMCE'nin resim yükleme URL'si
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False, # Django'nun mevcut loglayıcılarını devre dışı bırakmayın

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG', # DEBUG seviyesindeki ve daha yüksek tüm mesajları göster
            'class': 'logging.StreamHandler', # Konsola yaz
            'formatter': 'simple', # Basit format kullan
        },
    },
    'loggers': {
        # Kendi uygulamanızın loglayıcısı (örn. 'institutions' veya 'institution_media')
        # Bu, uygulamalarınızdaki loglama mesajlarını yakalar
        'institutions': { # 'institutions' uygulamanızın loglarını yakala
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False, # Bu loglayıcının mesajlarını üst loglayıcılara gönderme (çift loglamayı önler)
        },
        'institution_media': { # 'institution_media' uygulamanızın loglarını yakala
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Eğer admin.py'de 'institutions.admin' gibi belirli bir logger adı kullandıysanız,
        # onu da burada tanımlayabilirsiniz. Önceki cevabımda __name__ kullandık,
        # bu da 'institutions.admin' veya 'institution_media.admin' gibi isimler alacak.
        'django': { # Django'nun kendi iç logları için
            'handlers': ['console'],
            'level': 'INFO', # Django'nun genel logları için INFO seviyesi yeterli olabilir
            'propagate': False,
        },
        '': { # Kök loglayıcı (eğer yukarıda eşleşmeyen bir logger varsa)
            'handlers': ['console'],
            'level': 'WARNING', # Varsayılan olarak WARNING ve üzeri logları göster
            'propagate': True,
        },
    }
}

# 3. Allauth Özel Ayarları

ACCOUNT_AUTHENTICATION_METHOD = 'email' # Email ile giriş
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional' # Template olduğu için 'optional' en iyisidir
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# 4. Sosyal Hesap Sağlayıcıları (Dinamik ve Opsiyonel Yapı)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_SECRET', ''),
            'key': ''  # Google için genellikle boş bırakılır
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_TOKEN_VARIABLE': 'JS_SDK'
    }
}



# Image Processing Settings
WATERMARK_ENABLED = os.environ.get("WATERMARK_ENABLED", "False") == "True"
IMAGEKIT_DEFAULT_CACHEFILE_BACKEND = 'imagekit.cachefiles.backends.Simple'