# Generated by Django 5.0.14 on 2026-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url_external', models.URLField(blank=True, help_text='Dış bağlantı varsa burayı doldurun.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_footer', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Menü',
                'verbose_name_plural': 'Menüler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='samples/')),
            ],
        ),
    ]
